#!/bin/bash
#---------------------
# Testing /usr/bin/nova-* shebangs
#---------------------
set -e

BINARIES=('nova-api-metadata' 'nova-api-os-compute' 'nova-api' \
          'nova-cells' 'nova-manage' 'nova-policy' 'nova-rootwrap' \
          'nova-rootwrap-daemon' 'nova-status' 'nova-compute' \
          'nova-conductor' 'nova-console' 'nova-consoleauth' \
          'nova-dhcpbridge' 'nova-network' 'nova-novncproxy' \
          'nova-placement-api' 'nova-scheduler' 'nova-serialproxy' \
          'nova-spicehtml5proxy' 'nova-xvpvncproxy' 'nova-api-wsgi' \
          'nova-metadata-wsgi')

ret=0

for binary in "${BINARIES[@]}"; do
    if ! `dirname $0`/test-shebang.py $binary python2.7; then
        ret=1
    fi
done

exit $ret
