[DEFAULT]
debian-branch = stable/2024.1
upstream-tag = %(version)s
pristine-tar = True
upstream-branch = upstream-caracal

[buildpackage]
export-dir = ../build-area
prebuild = [ ! -f .launchpad.yaml ] || rm .launchpad.yaml
